# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Set version
      id: set_version
      run: echo "::set-output name=version::1.0.0-$GITHUB_RUN_NUMBER"        
    - name: Restore dependencies
      run: dotnet restore


    - name: List Contents Before Packaging
      run: ls -R Utils/bin/Release/
    
    - name: Build and pack NuGet package
      run: dotnet pack -c Release --no-build
    
    - name: List Contents After Packaging
      run: ls -R Utils/bin/Release/

      
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal
    - name: Nuget set access    
      run: dotnet nuget add source --username ${{ github.actor }} --password ${{ github.token }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/garethbirduk/index.json"
    - name: Nuget deploy Package
      run: dotnet nuget push Utils/bin/Release/**/*.nupkg --api-key ${{ secrets.GH_APIKEY }} --source "github"
