# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Set version
      id: set_version
      run: echo "::set-output name=version::1.0.0-$GITHUB_RUN_NUMBER"        
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Nuget set access
      run: dotnet nuget add source --username %GH_USERNAME% --password %GH_APIKEY% --store-password-in-clear-text --name github "https://nuget.pkg.github.com/garethbirduk/index.json"
    - name: Nuget Deploy Package
      run: dotnet nuget push Utils/bin/Release/**/*.nupkg --api-key %GH_APIKEY% --source "github"    
